In [3]:
#### RUN ME PLEASE ####
"""Use 'Shift + Enter' when focused on this cell."""
import numpy as np

# Python for DS Practice
## Data Science for Kaggle Decal Spring 2017


Welcome to the first pset. This should be a really simple intro to numpy. We are structuring it to get you familiar with the tools we will be using for this class. Make sure that you run the first cell before any others otherwise you'll get errors for not including the numpy package.

If you have trouble with any question, first consult any old notebooks. Especially those from class today.
Then, ask [Piazza](https://piazza.com/class/iy117z6nv30626?cid=9)! We'll try to get back to you asap through there. 

# Problem 1
Fill `fun_array` with values 1-100 using a numpy method. Use google to find the answer.

In [4]:
fun_array = np.arange(100)

# Problem 2 
Take the square root of each element in fun_array using numpy commands. Don't use a `for` loop

In [5]:
### YOUR CODE HERE
fun_array_sqrt = np.sqrt(fun_array)
fun_array_sqrt

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949,
        5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481,
        5.47722558,  5.56776436,  5.65685425,  5.74456265,  5.83095189,
        5.91607978,  6.        ,  6.08276253,  6.164414  ,  6.244998  ,
        6.32455532,  6.40312424,  6.4807407 ,  6.55743852,  6.63324958,
        6.70820393,  6.78232998,  6.8556546 ,  6.92820323,  7.        ,
        7.07106781,  7.14142843,  7.21110255,  7.28010989,  7.34846923,
        7.41619849,  7.48331477,  7.54983444,  7.61577311,  7.68114575,
        7.74596669,  7.81024968,  7.87400787,  7.93725393,  8.        ,
        8.06225775,  8.1240384 ,  8.18535277,  8.24621125,  8.30

# Problem 3
Fill this array with 100 random values. Your answer should use only a single method call like `np.<method>()`

In [13]:
random_array = np.random.uniform(10, size=100)
random_array

array([ 5.32973746,  1.76380301,  4.52884635,  3.92003095,  7.05087311,
        9.18357148,  5.21368855,  7.01844527,  9.771284  ,  8.05180266,
        7.1001374 ,  5.59095331,  2.4161708 ,  2.6332005 ,  1.05539258,
        9.09587952,  3.44038004,  7.47692959,  6.78904857,  9.94470107,
        1.74744333,  7.42756931,  1.60628892,  4.28937335,  9.60697614,
        4.67281947,  1.10442799,  6.97953011,  4.25241913,  2.40620601,
        1.8079472 ,  4.6236214 ,  2.23159073,  9.99318988,  3.50194354,
        2.0358931 ,  7.19423453,  4.27214693,  3.05456362,  6.42326362,
        3.77679257,  1.7686791 ,  8.7249592 ,  5.53340641,  1.4767564 ,
        6.08231925,  1.59391528,  4.32049016,  5.4026937 ,  8.17372381,
        2.05535833,  4.58389787,  3.030709  ,  3.3820696 ,  1.68165815,
        1.25127666,  6.7112826 ,  9.12049709,  8.52858956,  1.32120202,
        7.56281588,  8.71196428,  8.63755627,  7.51675831,  4.9541587 ,
        4.95038523,  4.78997102,  1.90277973,  7.34482208,  4.05

# Problem 4
Multiply each element in `random_array` by `5`. Do not use a `for` loop.

In [14]:
random_arrayx5 = random_array * 5
random_arrayx5

array([ 26.64868729,   8.81901505,  22.64423173,  19.60015477,
        35.25436556,  45.91785742,  26.06844275,  35.09222633,
        48.85642   ,  40.2590133 ,  35.50068698,  27.95476657,
        12.08085399,  13.16600249,   5.27696292,  45.4793976 ,
        17.20190022,  37.38464793,  33.94524284,  49.72350533,
         8.73721665,  37.13784657,   8.0314446 ,  21.44686677,
        48.0348807 ,  23.36409737,   5.52213997,  34.89765053,
        21.26209566,  12.03103007,   9.03973601,  23.11810699,
        11.15795367,  49.96594939,  17.50971769,  10.1794655 ,
        35.97117267,  21.36073467,  15.2728181 ,  32.11631811,
        18.88396286,   8.84339551,  43.62479599,  27.66703207,
         7.38378202,  30.41159625,   7.96957642,  21.60245082,
        27.01346852,  40.86861904,  10.27679166,  22.91948936,
        15.15354501,  16.91034799,   8.40829077,   6.25638332,
        33.556413  ,  45.60248545,  42.6429478 ,   6.60601008,
        37.81407942,  43.55982138,  43.18778135,  37.58

# Problem 5
Multiply matrix $X$ and multiply with $\vec{y}$ using numpy commands. Should be only 1 line.

In [19]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([1,2,3])
np.dot(X, np.transpose(y))

array([14, 32, 50])

# Problem 6
Get the shape of `X` and output it. Do it with and without a print() statement for full credit.

In [20]:
np.shape(X)

(3, 3)

# Problem 7
Fill in the missing code so that you can plot 

This is a very simple 2 line problem. You should read [the `matplotlib` documentation](http://matplotlib.org/users/pyplot_tutorial.html) regardless of how familiar you are with matplotlib. 

Alternatively, google how to plot a graph using matplotlib. You'll probably find an answer on stack overflow

I almost always copy and past matplotlib code whenever I need to use it.

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
X = np.linspace(0, 5, 500) #np.arange(500)

# These are just to represent actual training and testing 
training_accuracy = np.exp(-(X)) * np.exp(1.5) + 0.5
testing_accuracy = (X - 2.4)**2 + 1

### YOUR CODE BELOW ###
### END YOUR CODE ###

plt.title("Bias Variance")
plt.xlabel("Parameter Value ")
plt.ylabel("Error")
plt.legend(labels=['Training Error','Testing Error'])
axes = plt.gca()
axes.set_ylim([0,5])

# HOMEWORK SUBMISSION
We will be submitting work through gradescope. You must make your submission in pdf format so that we can easily process them using gradescope question matching.
## Saving the file as a pdf

In the menu bar, you simply follow
`File > Print Preview` 
Then print the webpage and Save as PDF. This differs per browser/OS so you may have to spend some time looking for this option to save. 

## Submitting
Go to [gradescope.com](https://gradescope.com/), and click on the box  that says `Add a course`. Type in `9KPPBM` to the course enrollment spot and you should be good to go. If you are not enrolled in the course, we will remove you from gradescope so please only enroll if we have sent you a permission numer. 

When you are in the course, navigate to `Problem Set 1`. On the submission page, select upload and upload the pdf you just downloaded. You will be required to label your questions appropriately.
